//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesData
    {
        public int RowNum { get; set; }
        public int Id { get; set; }
        public float Data { get; set; }
        public long Timestamp { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
